### ISSUE TITLE
Outstanding Issues

### ISSUE THREAD

**Issue by aidantwoods** [aidanwoods/parsedown#10]
As a starting point, its probably worth reviewing https://github.com/erusev/parsedown/issues to see where we are in terms of reported unfixed bugs and reopening them here. A reasonable number have already been fixed by changes over here so far (see: https://github.com/erusev/parsedown/issues/553), and some issues are probably questions/feature requests that can probably be left for now.

# Open Issues in Parsedown
(check if fixed)
## Bugs with sufficient information
- [x] https://github.com/erusev/parsedown/issues/161, safe mode
- [x] https://github.com/erusev/parsedown/issues/358, Parse inlineLink incorrectly if the link text is an URL
- [x] https://github.com/erusev/parsedown/issues/417, URL in `[...](link)` gets Double Linked
- [x] https://github.com/erusev/parsedown/issues/427, the last item of a list missing `<p></p>` tag
- [x] https://github.com/erusev/parsedown/issues/432, Link parse issue
- [x] https://github.com/erusev/parsedown/issues/474, Unexpected paragraph in unordered list
- [x] https://github.com/erusev/parsedown/issues/487, Bug with inlineUrl method - not consider already wrapped anchor with the same URL
- [x] https://github.com/erusev/parsedown/issues/497, Link allows javascript which could lead to XSS issues
- [x] https://github.com/erusev/parsedown/issues/504, Double Parsing!!
- [x] https://github.com/erusev/parsedown/issues/524, incorrect render for c#
- [x] https://github.com/erusev/parsedown/issues/529, Possible bug when rendering list
- [x] https://github.com/erusev/parsedown/issues/530, Cross-site scripting vulnerability in ParseDown
- [x] https://github.com/erusev/parsedown/issues/551, Inconsistent List Formatting With Linebreaks
- [ ] https://github.com/erusev/parsedown/issues/531, Parsedown does not treat emphasis tags (*, _, etc.) as literal when spaced out
- [x] https://github.com/erusev/parsedown/issues/528, Different result parsedown vs original due to new line
- [ ] https://github.com/erusev/parsedown/issues/508
- [ ] https://github.com/erusev/parsedown/issues/505
- [x] https://github.com/erusev/parsedown/issues/488 (fix started in https://github.com/erusev/parsedown/pull/489)
- [x] https://github.com/erusev/parsedown/issues/486
- [x] https://github.com/erusev/parsedown/issues/477
- [ ] https://github.com/erusev/parsedown/issues/466 (fix started in https://github.com/erusev/parsedown/pull/467)
- [x] ~~(duplicate of 362) https://github.com/erusev/parsedown/issues/463 (this is strictly speaking a commonmark violation)~~
- [ ] https://github.com/erusev/parsedown/issues/462
- [ ] https://github.com/erusev/parsedown/issues/461
- [x] https://github.com/erusev/parsedown/issues/454
- [ ] https://github.com/erusev/parsedown/issues/443
- [x] ~~(duplicate of 434) https://github.com/erusev/parsedown/issues/442~~
- [x] https://github.com/erusev/parsedown/issues/437
- [ ] https://github.com/erusev/parsedown/issues/435 (fix started in https://github.com/erusev/parsedown/pull/513)
- [ ] https://github.com/erusev/parsedown/issues/434
- [x] https://github.com/erusev/parsedown/issues/415
- [x] https://github.com/erusev/parsedown/issues/412
- [ ] https://github.com/erusev/parsedown/issues/411
- [x] https://github.com/erusev/parsedown/issues/407
- [x] https://github.com/erusev/parsedown/issues/405
- [ ] https://github.com/erusev/parsedown/issues/375
- [x] https://github.com/erusev/parsedown/issues/370 (there's a bug here, but not with the test case reported per commonmark – parsedown does some non-compliant things when determining tag nesting)
- [x] https://github.com/erusev/parsedown/issues/367
- [x] https://github.com/erusev/parsedown/issues/366
- [ ] https://github.com/erusev/parsedown/issues/365
- [ ] https://github.com/erusev/parsedown/issues/364
- [x] https://github.com/erusev/parsedown/issues/362
- [ ] https://github.com/erusev/parsedown/issues/360
- [x] https://github.com/erusev/parsedown/issues/356
- [ ] https://github.com/erusev/parsedown/issues/352
- [x] https://github.com/erusev/parsedown/issues/344
- [x] https://github.com/erusev/parsedown/issues/337
- [ ] https://github.com/erusev/parsedown/issues/324 (he's not wrong)
- [x] https://github.com/erusev/parsedown/issues/320
- [x] https://github.com/erusev/parsedown/issues/299
- [ ] https://github.com/erusev/parsedown/issues/292
- [x] https://github.com/erusev/parsedown/issues/287 (this probably doesn't happen anymore due to escaping methodology changes)
- [x] https://github.com/erusev/parsedown/issues/259
- [x] https://github.com/erusev/parsedown/issues/246
- [x] https://github.com/erusev/parsedown/issues/233
- [ ] https://github.com/erusev/parsedown/issues/198
- [x] ~~(duplicate of 362) https://github.com/erusev/parsedown/issues/174~~
- [x] https://github.com/erusev/parsedown/issues/107
- [x] https://github.com/erusev/parsedown/issues/100

## Bugs with insufficient information
- [ ] https://github.com/erusev/parsedown/issues/549
- [ ] https://github.com/erusev/parsedown/issues/527
- [x] https://github.com/erusev/parsedown/issues/517
- [x] https://github.com/erusev/parsedown/issues/468
- [x] https://github.com/erusev/parsedown/issues/397
- [x] https://github.com/erusev/parsedown/issues/389
- [x] https://github.com/erusev/parsedown/issues/383
- [x] https://github.com/erusev/parsedown/issues/379
- [x] https://github.com/erusev/parsedown/issues/378
- [x] https://github.com/erusev/parsedown/issues/288
- [x] https://github.com/erusev/parsedown/issues/270
- [x] https://github.com/erusev/parsedown/issues/266
- [x] https://github.com/erusev/parsedown/issues/232
- [x] https://github.com/erusev/parsedown/issues/193
- [x] https://github.com/erusev/parsedown/issues/173
- [x] https://github.com/erusev/parsedown/issues/75

## Meta bugs
- [x] https://github.com/erusev/parsedown/issues/213

## Feature Requests
- [x] https://github.com/erusev/parsedown/issues/510
- [x] ~~(duplicate of 510) https://github.com/erusev/parsedown/issues/554, MathJax~~
- [x] https://github.com/erusev/parsedown/issues/542
- [x] https://github.com/erusev/parsedown/issues/494
- [x] https://github.com/erusev/parsedown/issues/490
- [ ] https://github.com/erusev/parsedown/issues/473
- [x] https://github.com/erusev/parsedown/issues/472
- [x] https://github.com/erusev/parsedown/issues/471
- [x] https://github.com/erusev/parsedown/issues/470
- [x] https://github.com/erusev/parsedown/issues/460
- [x] https://github.com/erusev/parsedown/issues/457
- [x] https://github.com/erusev/parsedown/issues/422
- [x] https://github.com/erusev/parsedown/issues/413
- [x] https://github.com/erusev/parsedown/issues/401
- [x] https://github.com/erusev/parsedown/issues/371
- [x] https://github.com/erusev/parsedown/issues/348
- [x] https://github.com/erusev/parsedown/issues/339
- [x] https://github.com/erusev/parsedown/issues/338
- [x] https://github.com/erusev/parsedown/issues/306
- [x] https://github.com/erusev/parsedown/issues/304
- [x] https://github.com/erusev/parsedown/issues/112
- [x] https://github.com/erusev/parsedown/issues/102
- [x] https://github.com/erusev/parsedown/issues/101
- [x] https://github.com/erusev/parsedown/issues/99

## Questions
- [x] https://github.com/erusev/parsedown/issues/550
- [x] https://github.com/erusev/parsedown/issues/537
- [x] https://github.com/erusev/parsedown/issues/523
- [x] https://github.com/erusev/parsedown/issues/483
- [x] https://github.com/erusev/parsedown/issues/476
- [x] https://github.com/erusev/parsedown/issues/418 (answered by `setSafeMode`)
- [x] https://github.com/erusev/parsedown/issues/400
- [x] https://github.com/erusev/parsedown/issues/390
- [x] https://github.com/erusev/parsedown/issues/350
- [x] https://github.com/erusev/parsedown/issues/326
- [x] https://github.com/erusev/parsedown/issues/282
- [x] https://github.com/erusev/parsedown/issues/155

## Requests for CommonMark/GFM violations (marking all as done)
- [x] https://github.com/erusev/parsedown/issues/448
- [x] https://github.com/erusev/parsedown/issues/428 (I think)
- [x] https://github.com/erusev/parsedown/issues/416
- [x] https://github.com/erusev/parsedown/issues/399
- [x] https://github.com/erusev/parsedown/issues/301 (but meh, might be useful so could be moved to "feature request")
## Other, repo-specific (marking all as done for these purposes)
- [x] https://github.com/erusev/parsedown/issues/553, Housekeeping
- [x] https://github.com/erusev/parsedown/issues/532
- [x] https://github.com/erusev/parsedown/issues/526
- [x] https://github.com/erusev/parsedown/issues/516
- [x] https://github.com/erusev/parsedown/issues/503
- [x] https://github.com/erusev/parsedown/issues/438
- [x] https://github.com/erusev/parsedown/issues/159
- [x] https://github.com/erusev/parsedown/issues/83
## Other, unsure how to categorise
- [x] https://github.com/erusev/parsedown/issues/421
- [x] https://github.com/erusev/parsedown/issues/308

**Comment by aidantwoods** [comment]
I've now reviewed the first page plus those referenced in https://github.com/erusev/parsedown/issues/553.

**Comment by aidantwoods** [comment]
I have now categorised all 127 open issues from the Parsedown repository above. I have checked bugs which I do not feel require additional attention (and should be closed in the main repo if possible *provided that bug fixes from this repo are merged across*). Bugs that are unchecked are either unfixed or I'm unsure about them (either way they need an additional looking at).

I may have missed linking some duplicates, or non-optimally categorised things – please just suggest or make improvements in this case :)

I would suggest that we open issues here to cover non-duplicates from the unchecked items in "Bugs with sufficient information".

**Comment by PhrozenByte** [comment]
Great work! :heart: 

I don't think that it's necessary to open new Issues for the unchecked bugs above, this list should be sufficient to manage them. Discussions should still happen in the existing Issues. Maybe just a small hint that erusev/parsedown#554 is the latest Issue of this list, so that we can later add new Issues more easily.

What about all those open PRs? You've merged the most important already, but there are surely some more sensible PRs in the repo (not that I want to say that they should be merged immediately, just checked the same ways as you checked Issues).

**Comment by aidantwoods** [comment]
I think this issue probably isn't needed anymore, since I'm able to tag and close out solved issues in the main repo to keep things organised.

I didn't add any new issues, but figured I might as well tick everything that was closed in the main repo since this was last updated :)
